#!/bin/bash

list=$(zenity --radiolist --list \
  --title="Geps Downloader" \
  --column="no" --column="distro" 01 "debian" 02 "arch")

if [[ $list == "debian" ]]; then
  echo "monggo download debian"
  curl -L -o debian.iso https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-12.6.0-amd64-DVD-1.iso
elif [[ $list == "arch" ]]; then
  echo "monggo download arch"
  curl -L -o arch.iso https://mirror.citrahost.com/archlinux/iso/2024.07.01/archlinux-2024.07.01-x86_64.iso
else
  echo "iso ora iso diunduh"
fi
