#!/bin/env bash

yuros_notify() {
  if [[ $1 == 1 ]]; then
    echo "error $2, development building : failed"
  elif [[ $1 == 2 ]]; then
    echo "$2 file created"
  elif [[ $1 == 3 ]]; then
    echo "$2 file exist"
  elif [[ $1 == 4 ]]; then
    echo "$2 main  directory created"
  elif [[ $1 == 5 ]]; then
    echo "$2 main directory exist"
  elif [[ $1 == 6 ]]; then
    echo "$2 development directory created"
  elif [[ $1 == 7 ]]; then
    echo "$2 development directory exist"
  else
    echo "function parameter 1 is empty"
  fi
}
